title: Introvert Guide
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://wjcchwsk.github.io

aux_links:
  GitHub Repository: https://github.com/wjcchwsk/introvert
