title: Introvert Guide
description: Introvert's Guide to Technical Writing
theme: just-the-docs

url: https://wjcchwsk.github.io

aux_links:
  GitHub Repository: https://github.com/wjcchwsk/introvert
